### ISSUE TITLE
No markers within Stormwind shown in Elwynn Forest

### ISSUE THREAD

**Issue by p3lim** [Nevcairiel/HereBeDragons#3]
Might be just one example of cases of pins not drawing on parent maps of submaps like this though, just one example I encountered.

This was with HBD+HBDP 2.0 as of [this](https://github.com/Nevcairiel/HereBeDragons/commit/61383763a1ce7b87379d50b534150693e2d17ab7) commit (latest one to date).

**Comment by Nevcairiel** [comment]
Elwynn Forest is not actually the parent map of Stormwind, though, so this is somewhat intentional behavior.

Stormwind (84) reports as parent directly Eastern Kingdoms (13). HBD can only go off of the map data the game provides. Stormwind and Elwynn are neighboring zones only.

The way Stormwind is drawn on the Elwynn map, I don't think it would result in any half-accurate mapping anyway.

**Comment by p3lim** [comment]
Fair enough 👍
